project:
  type: website

website:
  title: "ISSS608-VAA"
  navbar:
    left: 
      - href: index.qmd
        text: ğŸ  Home
      - text: "ğŸ™‹â€â™‚ï¸ Hands-on Exercise"
        menu: 
          - text: "Hands-on Exercise 1"
            href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.html"
          - text: "Hands-on Exercise 2"
            
          - text: "Hands-on Exercise 3"
            
          - text: "Hands-on Exercise 4"
            
          - text: "Hands-on Exercise 5"
            
      - text: "ğŸ§‘â€ğŸ«ï¸ In-class Exercise"
        menu: 
          - text: " In-class Exercise 1"
            
      - text: "âœï¸ï¸ Take-home Exercise"
        menu: 
          - text: "  Take-home Exercise 1"
    right:
      
      - icon: github
        href: https://github.com/cjh202311
        aria-label: Github
      - icon: bar-chart-fill
        href: https://public.tableau.com/
        aria-label: Tableau
format:     
  html:
    theme: Quartz
    css: styles.css
    toc: true

editor: visual

